# Based on steps outlined at https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-github-actions?tabs=userlevel%2CCLI

name: CD Dev

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  CD-Dev:
    uses: ./.github/workflows/deployment.yml
    with:
      rg: 'TNF-Dev'
      uniquelabel: 'tnfdev'
      apicsprojpath: './src/STO.Api/STO.Api.csproj'
      apidotnetoutputpath: './src/STO.Api/output'
      blazorwasmcsprojpath: './src/STO.Wasm/STO.Wasm.csproj'
      servicestestscsprojpath: './src/STO.Services.Tests/STO.Services.Tests.csproj'
      servicestestspath: './src/STO.Services.Tests'
      blazorwasmdotnetoutputpath: './src/STO.Wasm/output'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
