# Based on steps outlined at https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-github-actions?tabs=userlevel%2CCLI

name: CD Dev

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  CD-Prod:
    uses: ./.github/workflows/deployment.yml
    with:
      rg: 'SportsTeamOrganiserDev'
      uniquelabel: 'stodev'
      csprojpath: './src/STO.csproj'
      dotnetoutputpath: './src/output'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
