# Based on steps outlined at https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-github-actions?tabs=userlevel%2CCLI

name: CD Prod

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  CD-Prod:
    uses: ./.github/workflows/deployment.yml
    with:
      rg: 'TNF-Prod'
      uniquelabel: 'tnfprod'
      blazorservercsprojpath: './src/STO.Server/STO.Server.csproj'
      blazorserverdotnetoutputpath: './src/STO.Server/output'
      apicsprojpath: './src/STO.Api/STO.Api.csproj'
      apidotnetoutputpath: './src/STO.Api/output'
      blazorwasmcsprojpath: './src/STO.Server/STO.Server.csproj'
      blazorwasmdotnetoutputpath: './src/STO.Server/output'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
