name: CD Prod

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  CD-Prod:
    uses: ./.github/workflows/deployment.yml
    with:
      rg: 'SportsTeamOrganiser'
      uniquelabel: 'stoprod'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS_MKNETPROD }}
      azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
