# Based on steps outlined at https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-github-actions?tabs=userlevel%2CCLI

name: Azure Deployment

on:
  workflow_call:
      inputs:
        rg:
          type: string
          required: true
        uniquelabel:
          type: string
          required: true
        blazorservercsprojpath:
          type: string
          required: true
        blazorserverdotnetoutputpath:
          type: string
          required: true
        apicsprojpath:
            type: string
            required: true
        apidotnetoutputpath:
            type: string
            required: true
        blazorwasmcsprojpath:
            type: string
            required: true
        blazorwasmdotnetoutputpath:
            type: string
            required: true
      secrets:
        azure-credentials:
          required: true
        azure-subscription:
          required: true
   
jobs:
  Deploy-Infrastructure:
# Setup
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@main

    - name: azure-login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azure-credentials }}
        
    - name: setup-dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

# Bicep
    - name: bicep-install
      run: |
        az config set bicep.use_binary_from_path=False
        az bicep install

    - name: bicep-deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.azure-subscription }}
        resourceGroupName: ${{ inputs.rg }}
        template: ./bicep/main.bicep
        failOnStdErr: false
        parameters: 'uniqueName=${{ inputs.uniquelabel }}'

# Blazor Server code
    - name: bicep-output-blazorservername
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g ${{ inputs.rg }} --name main --query properties.outputs.BlazorServerName.value -o tsv)
          echo "BlazorServerName=$outputValue" >> $GITHUB_ENV   

    - name: dotnet-build-publish-blazorserver
      run: |
        dotnet restore ${{ inputs.blazorservercsprojpath }}
        dotnet build ${{ inputs.blazorservercsprojpath }} --configuration Release
        dotnet publish ${{ inputs.blazorservercsprojpath }} -c Release -o ${{ inputs.blazorserverdotnetoutputpath }}

    - name: azure-deploy-webapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.BlazorServerName }}
        package: '${{ inputs.blazorserverdotnetoutputpath }}'

# API code
    - name: bicep-output-apiname
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g ${{ inputs.rg }} --name main --query properties.outputs.apiName.value -o tsv)
          echo "ApiName=$outputValue" >> $GITHUB_ENV   

    - name: dotnet-build-publish-api
      run: |
        dotnet restore ${{ inputs.apicsprojpath }}
        dotnet build ${{ inputs.apicsprojpath }} --configuration Release
        dotnet publish ${{ inputs.apicsprojpath }} -c Release -o ${{ inputs.apidotnetoutputpath }}

    - name: azure-deploy-api
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.ApiName }}
        package: '${{ inputs.apidotnetoutputpath }}'

# Blazor Wasm code
    - name: bicep-output-blazorwasmname
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g ${{ inputs.rg }} --name main --query properties.outputs.blazorWasmName.value -o tsv)
          echo "BlazorWasmName=$outputValue" >> $GITHUB_ENV   

    - name: dotnet-build-publish-api
      run: |
        dotnet restore ${{ inputs.blazorwasmcsprojpath }}
        dotnet build ${{ inputs.blazorwasmcsprojpath }} --configuration Release
        dotnet publish ${{ inputs.blazorwasmcsprojpath }} -c Release -o ${{ inputs.blazorwasmdotnetoutputpath }}

    - name: azure-deploy-api
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.BlazorWasmName }}
        package: '${{ inputs.blazorwasmdotnetoutputpath }}'
