# Based on steps outlined at https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-github-actions?tabs=userlevel%2CCLI

name: Azure Deployment

on:
  workflow_call:
      inputs:
        rg:
          type: string
          required: true
        uniquelabel:
          type: string
          required: true
        blazorservercsprojpath:
          type: string
          required: true
        blazorserverdotnetoutputpath:
          type: string
          required: true
        apicsprojpath:
          type: string
          required: true
        apidotnetoutputpath:
          type: string
          required: true
      secrets:
        azure-credentials:
          required: true
        azure-subscription:
          required: true
   
jobs:
  Deploy-Infrastructure:
# Setup
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@main

    - name: azure-login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azure-credentials }}
        
    - name: setup-dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

# Bicep
    - name: bicep-install
      run: |
        az config set bicep.use_binary_from_path=False
        az bicep install

    - name: bicep-deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.azure-subscription }}
        resourceGroupName: ${{ inputs.rg }}
        template: ./bicep/main.bicep
        failOnStdErr: false
        parameters: 'uniqueName=${{ inputs.uniquelabel }}'

  Deploy-Apps:
    runs-on: ubuntu-latest
    steps:

# API code
    - name: api-dotnet-build-publish
      run: |
        dotnet restore ${{ inputs.apicsprojpath }}
        dotnet build ${{ inputs.apicsprojpath }} --configuration Release
        dotnet publish ${{ inputs.apicsprojpath }} -c Release -o ${{ inputs.apidotnetoutputpath }}

    - name: api-azure-deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'api-${{ inputs.uniquelabel }}'
        package: '${{ inputs.apidotnetoutputpath }}'

# Blazor Server code
    - name: blazorserver-dotnet-build-publish
      run: |
        dotnet restore ${{ inputs.blazorservercsprojpath }}
        dotnet build ${{ inputs.blazorservercsprojpath }} --configuration Release
        dotnet publish ${{ inputs.blazorservercsprojpath }} -c Release -o ${{ inputs.blazorserverdotnetoutputpath }}

    - name: blazorserver-azure-deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'blazorserver-${{ inputs.uniquelabel }}'
        package: '${{ inputs.blazorserverdotnetoutputpath }}'

# Blazor Wasm code
    - name: blazorwasm-dotnet-build-publish
      run: |
        dotnet restore ${{ inputs.blazorwasmcsprojpath }}
        dotnet build ${{ inputs.blazorwasmcsprojpath }} --configuration Release
        dotnet publish ${{ inputs.blazorwasmcsprojpath }} -c Release -o ${{ inputs.blazorwasmdotnetoutputpath }}

    - name: blazorwasm-azure-deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'blazorwasm-${{ inputs.uniquelabel }}'
        package: '${{ inputs.blazorwasmdotnetoutputpath }}'
