# Based on steps outlined at https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-github-actions?tabs=userlevel%2CCLI

name: Azure Deployment

on:
  workflow_call:
      inputs:
        rg:
          type: string
          required: true
        uniquelabel:
          type: string
          required: true
        csprojpath:
          type: string
          required: true
        dotnetoutputpath:
          type: string
          required: true
      secrets:
        azure-credentials:
          required: true
        azure-subscription:
          required: true
   
jobs:
  Deploy-Infrastructure:
# Setup
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@main

    - name: azure-login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azure-credentials }}
        
    - name: setup-dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

# Bicep
    - name: bicep-install
      run: |
        az config set bicep.use_binary_from_path=False
        az bicep install

    - name: bicep-deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.azure-subscription }}
        resourceGroupName: ${{ inputs.rg }}
        template: ./bicep/main.bicep
        failOnStdErr: false
        parameters: 'uniqueName=${{ inputs.uniquelabel }}'

# Web App code
    - name: bicep-output-webappname
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g ${{ inputs.rg }} --name main --query properties.outputs.webAppName.value -o tsv)
          echo "WebAppName=$outputValue" >> $GITHUB_ENV   

    - name: dotnet-build-publish-webapp
      run: |
        dotnet restore ${{ inputs.csprojpath }}
        dotnet build ${{ inputs.csprojpath }} --configuration Release
        dotnet publish ${{ inputs.csprojpath }} -c Release -o ${{ inputs.dotnetoutputpath }}

    - name: azure-deploy-webapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.WebAppName }}
        package: '${{ inputs.dotnetoutputpath }}'

# API code
    - name: bicep-output-apiwebappname
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g ${{ inputs.rg }} --name main --query properties.outputs.apiWebAppName.value -o tsv)
          echo "ApiWebAppName=$outputValue" >> $GITHUB_ENV   

    - name: dotnet-build-publish-apiwebapp
      run: |
        dotnet restore ${{ inputs.apicsprojpath }}
        dotnet build ${{ inputs.apicsprojpath }} --configuration Release
        dotnet publish ${{ inputs.apicsprojpath }} -c Release -o ${{ inputs.apidotnetoutputpath }}

    - name: azure-deploy-webapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.ApiWebAppName }}
        package: '${{ inputs.apidotnetoutputpath }}'
