name: Test

on:
    workflow_dispatch:
            
            
jobs:
    Deploy-Infrastructure:
  # Setup
      runs-on: ubuntu-latest
      steps:

      - name: checkout
        uses: actions/checkout@main

      - name: azure-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

  # Blazor Wasm code
      - name: blazorwasm-dotnet-build-publish
        run: |
          dotnet restore './src/STO.Wasm/STO.Wasm.csproj'
          dotnet build './src/STO.Wasm/STO.Wasm.csproj'
          dotnet publish './src/STO.Wasm/STO.Wasm.csproj' -c Release -o './src/STO.Wasm/output'

      - name: blazorwasm-azure-deploy
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'blazorwasm-tnfdev'
          package: './src/STO.Wasm/output'
